### ISSUE TITLE
Webcam is not working on windows x86 build

### ISSUE THREAD

**Issue by DaBlitzStein** [EnoxSoftware/MarkerBasedARSample#1]
The android build works.

**Comment by EnoxSoftware** [comment]
the image of WebCamera is displayed?

**Comment by DaBlitzStein** [comment]
Yes, the image is displayed, the code is verified, but the 3d objects are not here.

**Comment by EnoxSoftware** [comment]
Marker will be detected when you are using the outer camera(WebCamTexture.devices.isFrontFacing is false).
Since the Mat in the case of inner camera(WebCamTexture.devices.isFrontFacing is true) has reversed from left to right, the marker will not be detected.

**Comment by tomihr** [comment]
Hello.
I also have problems with Web cam detection.
My camera preview in Unity Editor is flipped from left to right, and marker is not detected.
![screenshot](https://cloud.githubusercontent.com/assets/439072/14041974/091bb4c2-f276-11e5-8f5b-96a4729ca711.jpg)

**Comment by EnoxSoftware** [comment]
Please add "Core.flip (rgbaMat, rgbaMat, 1);" to WebCamTextureMarkerBasedARSample.cs.

								Mat rgbaMat = webCamTextureToMatHelper.GetMat ();
 
 								//for frontFaceingCamera
 								Core.flip (rgbaMat, rgbaMat, 1);
 
 								markerDetector.processFrame (rgbaMat, 1);
